name: frontend
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  injectable: ^2.0.1
  get_it: ^7.2.0
  go_router: ^5.2.0
  http_parser: ^4.0.2
  file_picker: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.0.1
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
