#!/bin/bash

v1="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
v2="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
v3="AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME"
v4="AWS_REGION=$AWS_REGION"
v5="DATABASE_URL=$DATABASE_URL"
v6="DATABASE_NAME=$DATABASE_NAME"
v7="BACKEND_URL=$BACKEND_URL"
v8="JWT_SECRET=$JWT_SECRET"
v9="BCRYPT_STRENGTH=$BCRYPT_STRENGTH"

echo "BACKEND_ENV_VARS=$v1 $v2 $v3 $v4 $v5 $v6 $v7 $v8 $v9" >> "$GITHUB_ENV"
