name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  Backend:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Test
        run: cd backend && ./gradlew test
      - name: Build
        run: cd backend && ./gradlew build

  Frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: cd frontend && flutter pub get
      - name: Build DI tree
        run: cd frontend && flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Test
        run: cd frontend && flutter test
